import requests
import uuid

# Production URL
BASE_URL = "https://dbiller-production.up.railway.app"
# Use the license key generated by the user in the previous turn
LICENSE_KEY = "8a898bac-3f5c-4b46-ba83-645b102876bc" 

def test_register():
    print(f"Testing Registration on {BASE_URL}")
    
    # Randomize username to avoid conflicts if re-running
    username = f"testuser_{uuid.uuid4().hex[:6]}"
    password = "password123"
    device_id = f"device_{uuid.uuid4().hex[:6]}"
    
    payload = {
        "username": username,
        "password": password,
        "device_id": device_id,
        "license_key": LICENSE_KEY,
        "store_name": "Test Store"
    }
    
    print(f"Sending payload: {payload}")
    
    try:
        response = requests.post(f"{BASE_URL}/register", data=payload)
        
        print(f"Status Code: {response.status_code}")
        print(f"Response Body: {response.text}")
        
        if response.status_code == 200:
            print("✅ Registration Successful!")
        else:
            print("❌ Registration Failed!")
            
    except Exception as e:
        print(f"❌ Exception occurred: {e}")

if __name__ == "__main__":
    test_register()
